apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clip
  template:
    metadata:
      labels:
        app: clip
    spec:
      containers:
      - name: clip
        image: clip-service:latest
        volumeMounts:
        - mountPath: /models
          name: models-volume
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc 